import { Project } from './types'

export const PROJECTS: Project[] = [
  {
    id: 'portfolio',
    title: 'Afraz \u2014 Portfolio',
    shortTitle: 'Portfolio',
    description:
      'A personal portfolio that pairs clean, technical clarity with playful interaction design.',
    longDescription:
      'A developer portfolio built to feel alive: smooth scroll-driven narratives, micro-interactions on every element, and a calm technical interface. Fast, accessible, and deliberately interactive \u2014 designed to show range without sacrificing focus.',
    category: 'web',
    tags: ['Design', 'Frontend', 'Interaction'],
    built: [
      'Personal portfolio site',
      'Project showcase archive',
      'Contact and social integration',
    ],
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    year: '2026',
    url: 'https://afrazcreates.vercel.app/',
    theme: {
      accent: '#5B9BFF',
      accentLight: '#9CC4FF',
      accentGlow: 'rgba(91, 155, 255, 0.3)',
      bg: '#07080d',
      bgSecondary: '#0e1018',
      text: '#f4f6fa',
      visualGradient: 'linear-gradient(135deg, #0b1020, #141a2e)',
      gridOpacity: 0.3,
    },
    visualType: 'particles',
    world: {
      atmosphere: 'developer',
      bg: '#06070c',
      bgSecondary: '#0c0f1a',
      text: '#eef2fb',
      textSecondary: '#9aa8cc',
      textMuted: '#5a6689',
      accent: '#7FB0FF',
      accentLight: '#B4D2FF',
      glowColor: '#7FB0FF',
      glowAlpha: 0.34,
      borderAlpha: 0.08,
      gridAlpha: 0.28,
      gridSize: 44,
      grain: 0.032,
      cursorColor: '#B4D2FF',
      horizon: '#101a33',
      horizonAlpha: 0.55,
      underColor: '#060911',
    },
  },
  {
    id: 'coffee-house',
    title: 'Coffee House',
    shortTitle: 'Coffee House',
    description:
      'A warm, editorial coffee-house experience \u2014 story, menu, and atmosphere in one calm space.',
    longDescription:
      'A specialty coffee house in Riyadh, presented with quiet luxury: warm wood tones, soft light, and a cup made with attention. From the philosophy to the handwritten cups, the site turns browsing a menu into a slow ritual.',
    category: 'client',
    tags: ['Branding', 'Frontend', 'UX'],
    built: [
      'Story-driven café website',
      'Menu and reservation flows',
      'Bilingual EN / AR interface',
    ],
    tech: ['React', 'TypeScript', 'Supabase'],
    year: '2026',
    url: 'https://housecoffee.vercel.app/',
    theme: {
      accent: '#E2A45C',
      accentLight: '#F1C99B',
      accentGlow: 'rgba(226, 164, 92, 0.28)',
      bg: '#0f0a07',
      bgSecondary: '#1a120c',
      text: '#f5f0eb',
      visualGradient: 'linear-gradient(135deg, #2c170d, #160d08)',
      gridOpacity: 0.12,
    },
    visualType: 'waves',
    world: {
      atmosphere: 'coffee',
      bg: '#0d0906',
      bgSecondary: '#171009',
      text: '#f7f1e9',
      textSecondary: '#cdbba6',
      textMuted: '#7d6b58',
      accent: '#EFC08B',
      accentLight: '#F6D9B3',
      glowColor: '#EFC08B',
      glowAlpha: 0.18,
      borderAlpha: 0.09,
      gridAlpha: 0.03,
      gridSize: 120,
      grain: 0.05,
      cursorColor: '#F6D9B3',
      horizon: '#3a2416',
      horizonAlpha: 0.55,
      underColor: '#080504',
    },
  },
  {
    id: 'nexus-2027',
    title: 'NEXUS 2027',
    shortTitle: 'NEXUS',
    description:
      'A futuristic three-day technology event \u2014 geometric, electric, and registration-ready.',
    longDescription:
      'An event platform for NEXUS 2027 \u2014 three days where the next generation of technology is built, tested, and shown in person. Geometric structures, electric violet and blue, precise grid systems, and futuristic motion design create an experience that feels like it arrived from the future.',
    category: 'web',
    tags: ['Concept', 'Animation', 'Design'],
    built: [
      'Event landing and registration',
      'Schedule, speakers and exhibitors',
      'Live countdown and program data',
    ],
    tech: ['Next.js', 'LangChain', 'PostgreSQL'],
    year: '2026',
    url: 'https://nexus2027.vercel.app/',
    theme: {
      accent: '#8A8CF5',
      accentLight: '#A5B4FC',
      accentGlow: 'rgba(138, 140, 245, 0.34)',
      bg: '#050510',
      bgSecondary: '#0a0a1a',
      text: '#e8e8ff',
      visualGradient: 'linear-gradient(135deg, #1a0033, #0d1b2a)',
      gridOpacity: 0.5,
    },
    visualType: 'geometry',
    world: {
      atmosphere: 'nexus',
      bg: '#04040c',
      bgSecondary: '#0a0f26',
      text: '#e7ebff',
      textSecondary: '#9aa2d3',
      textMuted: '#5c6897',
      accent: '#8A8CF5',
      accentLight: '#A5B4FC',
      glowColor: '#8A8CF5',
      glowAlpha: 0.48,
      borderAlpha: 0.1,
      gridAlpha: 0.34,
      gridSize: 56,
      grain: 0.028,
      cursorColor: '#A5B4FC',
      horizon: '#23276b',
      horizonAlpha: 0.6,
      underColor: '#180524',
    },
  },
  {
    id: 'pothole-filler',
    title: 'Pothole Filler',
    shortTitle: 'Pothole',
    description:
      'A community utility that turns a photo into a fixed street \u2014 report, route, resolve.',
    longDescription:
      'PotholeFix connects citizens with the authorities that fix their streets. Snap a photo, pin the exact location, and the report lands in the right hands \u2014 fast, transparent, and effective. Sometimes the best design is invisible shared infrastructure.',
    category: 'concepts',
    tags: ['Utility', 'Frontend', 'Minimal'],
    built: [
      'Pothole reporting flow',
      'GPS location pinning and photo upload',
      'Authority routing and status tracking',
    ],
    tech: ['TypeScript', 'Node.js', 'Express', 'PostgreSQL'],
    year: '2026',
    url: 'https://phfiller.vercel.app/',
    theme: {
      accent: '#F5A623',
      accentLight: '#FFCE7A',
      accentGlow: 'rgba(245, 166, 35, 0.3)',
      bg: '#0c0a06',
      bgSecondary: '#15110a',
      text: '#f5f2ea',
      visualGradient: 'linear-gradient(135deg, #1c150a, #2b210e)',
      gridOpacity: 0.25,
    },
    visualType: 'grid',
    world: {
      atmosphere: 'infra',
      bg: '#0a0906',
      bgSecondary: '#141209',
      text: '#f5f2ea',
      textSecondary: '#c0b9a4',
      textMuted: '#6d6752',
      accent: '#FBA94C',
      accentLight: '#FFD188',
      glowColor: '#FBA94C',
      glowAlpha: 0.26,
      borderAlpha: 0.09,
      gridAlpha: 0.2,
      gridSize: 100,
      grain: 0.04,
      cursorColor: '#FFD188',
      horizon: '#2e2410',
      horizonAlpha: 0.55,
      underColor: '#080705',
    },
  },
]